#ifndef __MISC__
#define __MISC__

typedef enum {
WATCH_STATE_IDLE =            0,
WATCH_STATE_DETECT_WATCH =    1,
WATCH_STATE_ERASE_WATCH =     2,
WATCH_STATE_START_BURN =      3,
WATCH_STATE_WAIT_START =      4,
WATCH_STATE_BURN =            5,
WATCH_STATE_WAIT_BURN =       6,
WATCH_STATE_FINISH_BURN =     7,
WATCH_STATE_WAIT_FINISH =     8,
WATCH_STATE_WAIT_CODE_XFR =   9,
WATCH_STATE_TEST_WATCH =      10,
WATCH_STATE_REMOVED =         11,
} WATCH_HANDLING_STATES;




#endif